#!/bin/bash
set -eu

if [ "DOCKERFILE_PATH" = "" ]; then
	DOCKER_FILE_PATH_ARG=""
else
	echo $DOCKERFILE_PATH |grep : >/dev/null && \
	 BUILDARG=$(echo $DOCKERFILE_PATH | awk -F: '{for( i=1; i< NF; i++) {print "--build-arg", $i}; print " -f",$NF }') || \
	 BUILDARG="-f $DOCKERFILE_PATH"
fi

docker build --build-arg $BUILD_ARG} -t $IMAGE_NAME .
